---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run flake8
        run: flake8 resources/

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Set up Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version: 3.12

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run static analysis
        run: bandit -q -r resources/
