---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  style-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.12

      - name: Setup task
        uses: arduino/setup-task@v2

      - name: Run lint
        run: task lint-flake8 -v

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4.1.7

      - name: Set up Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.12

      - name: Setup task
        uses: arduino/setup-task@v2

      - name: Run static analysis
        run: task lint-bandit -v